home/home/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('quotes.urls')),
    path('users/', include('users.urls')),
]

home/quotes/urls.py
from django.urls import path
from . import views

app_name = 'quotes'

urlpatterns = [
    path('', views.main, name='main'),
    path('create_quote/', views.create_quote, name='create_quote'),
    path('create_author/', views.create_author, name='create_author'),
    path('details/<int:quote_id>/', views.details, name='details'),
    path('author_detail/<int:author_id>/', views.author_detail, name='author_detail'),
    path('delete/<int:quote_id>/', views.delete_quote, name='delete'),
    path('search_in_tags/<str:tag>/', views.search_in_tags, name='search_in_tags'),
    path('top_ten_tags/', views.top_ten_tags, name='top_ten_tags')
]

home/users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('register/', views.signupuser, name='register'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
]

home/quotes/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models
from django.contrib.postgres.fields import ArrayField
from datetime import date


class Authors(models.Model):
    author_id = models.AutoField(primary_key=True)
    fullname = models.CharField(max_length=255)
    born_date = models.DateField()
    born_location = models.CharField(max_length=255)
    description = models.TextField(max_length=2000)

    def __str__(self):
        return self.fullname

    class Meta:
        managed = False
        db_table = 'authors'


class Quotes(models.Model):
    quote_id = models.AutoField(primary_key=True)
    tags = ArrayField(models.TextField(max_length=255))
    author = models.ForeignKey(Authors, on_delete=models.SET_DEFAULT, db_column='author', default='Stas')
    quote = models.TextField(max_length=2000)

    class Meta:
        managed = False
        db_table = 'quotes'

home/users/models.py
from django.db import models

# Create your models here.

home/quotes/forms.py
from django import forms
from .models import Quotes, Authors

class QuoteForm(forms.ModelForm):
    tags = forms.CharField(max_length=20,
                           required=True,
                           widget=forms.TextInput(attrs={'placeholder': 'Enter tags separated by ","'}))
    author = forms.ModelChoiceField(queryset=Authors.objects.all(),
                                    required=True)
    quote = forms.CharField(max_length=1000,
                            required=True,
                            widget=forms.TextInput())

    class Meta:
        model = Quotes
        fields = ['tags', 'author', 'quote']

    def clean_tags(self):
        tags = self.cleaned_data['tags'].split(',')
        return [tag.strip() for tag in tags]

class AuthorsForm(forms.ModelForm):
    fullname = forms.CharField(max_length=100,
                               required=True,
                               widget=forms.TextInput())
    born_date = forms.DateField(input_formats=['%d.%m.%Y'],
                                required=True,
                                error_messages={'invalid': 'Enter date in format "dd.mm.YYYY"'})
    born_location = forms.CharField(max_length=100,
                                required=True,
                                widget=forms.TextInput())
    description = forms.CharField(max_length=100,
                                required=True,
                                widget=forms.TextInput())

    class Meta:
        model = Authors
        fields = ['fullname', 'born_date', 'born_location', 'description']

home/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

class RegisterForm(UserCreationForm):
    username = forms.CharField(max_length=100,
                               required=True,
                               widget=forms.TextInput())

    password1 = forms.CharField(max_length=50,
                                required=True,
                                widget=forms.TextInput())

    password2 = forms.CharField(max_length=50,
                                required=True,
                                widget=forms.TextInput())

    class Meta:
        model = User
        fields = ['username', 'password1', 'password2']

class LoginForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ['username', 'password']

home/quotes/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.core.paginator import Paginator
from .models import Quotes, Authors
from .forms import QuoteForm, AuthorsForm
import itertools


def main(request):
    quotes_list = Quotes.objects.all()
    paginator = Paginator(quotes_list, 10)
    page = request.GET.get('page')
    text = 'Main'
    quotes = paginator.get_page(page)
    return render(request, 'quotes/index.html', {'quotes': quotes, 'text': text})


def create_quote(request):
    form = QuoteForm()
    if request.method == 'POST':
        form = QuoteForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(to='quotes:main')
    return render(request, 'quotes/create_quote.html', context={'form': form})


def create_author(request):
    form = AuthorsForm()
    if request.method == 'POST':
        form = AuthorsForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(to='quotes:main')
    return render(request, 'quotes/create_author.html', context={'form': form})


def author_detail(request, author_id):
    author = get_object_or_404(Authors, author_id=author_id)
    return render(request, 'quotes/author_detail.html', {'author': author})


def details(request, quote_id):
    quote = get_object_or_404(Quotes, quote_id=quote_id)
    return render(request, 'quotes/details.html', {'quote': quote})


def delete_quote(request, quote_id):
    Quotes.objects.get(pk=quote_id).delete()
    return redirect(to='quotes:main')


def tags_list_to_str(tags):
    if len(tags) >= 1:
        tags = ', '.join(tags)
    elif len(tags) == 1:
        tags = tags[0]
    return tags


def search_in_tags(request, tag):
    quotes = Quotes.objects.filter(tags__icontains=tag)
    text = f'Search by "{tag}"'
    return render(request, 'quotes/search_result.html', {'quotes': quotes, 'text': text})


def top_ten_tags(request):
    tags = Quotes.objects.values_list('tags', flat=True)
    tags_list = list(itertools.chain.from_iterable(tags))
    tags_set = set(tags_list)
    result = []
    for tag in tags_set:
        count = tags_list.count(tag)
        result.append([tag, count])
    tags = sorted(result, key=lambda x: x[1], reverse=True)[:10]
    print(tags)
    return render(request, 'quotes/top_ten_tags.html', {'tags': tags})

home/users/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.shortcuts import render, redirect
from .forms import RegisterForm, LoginForm

def signupuser(request):
    if request.user.is_authenticated:
        return redirect(to='noteapp:main')

    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(to='quotes:main')
        else:
            return render(request, 'users/register.html', context={'form': RegisterForm()})

    return render(request, 'users/register.html', context={'form': RegisterForm()})

def user_login(request):
    if request.user.is_authenticated:
        return redirect('main')

    if request.method == 'POST':
        user = authenticate(username=request.POST['username'], password=request.POST['password'])
        if user is None:
            messages.error(request, 'Username or password didn\'t match.')
            return redirect(to='users:login')
        login(request, user)
        return redirect(to='quotes:main')

    return render(request, 'users/login.html', context={'form': LoginForm()})

@login_required
def user_logout(request):
    logout(request)
    return redirect(to='quotes:main')

home/quotes/templates/quotes/author_detail.html
{% extends "quotes/base.html" %}

{% block content %}
<div>
    <label>Fullname:
        {{ author.fullname }}
    </label>
    <label>Born location:
        {{ author.born_location }}
    </label>
    <label>Born date:
        {{ author.born_date }}
    </label>
    <label>Description:
        {{ author.description }}
    </label>
</div>
{% endblock %}

home/quotes/templates/quotes/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <title>Note information</title>
    <link rel="stylesheet" href="https://unpkg.com/@picocss/pico@latest/css/pico.min.css"/>
    {% load static %}
    <link rel="stylesheet" href="{% static 'quotes/style.css' %}">
</head>
<body>
<main class="container">
    <nav style="margin-bottom: 20px; border-bottom: 2px solid; padding-right: 0px">
        <ul>
            <li><a href="/">Main page</a></li>
            <li><a href="{% url 'quotes:top_ten_tags' %}">Top ten</a></li>
        </ul>
        {% if user.is_authenticated %}
        <ul>
            <li><a href="{% url 'quotes:create_author' %}" role="button">Add author</a></li>
            <li><a href="{% url 'quotes:create_quote' %}" role="button">Add quote</a></li>
            <li><a class="logout" href="{% url 'users:logout' %}">Log out</a></li>
        </ul>
        {% else %}
        <ul>
            <li><a href="{% url 'users:login' %}" role="button">Log in</a></li>
            <li><a href="{% url 'users:register' %}" role="button">Register</a></li>
        </ul>
        {% endif %}
    </nav>
    {% block content %}
    {% endblock %}
</main>
</body>
</html>

home/quotes/templates/quotes/create_author.html
{% extends "quotes/base.html" %}

{% block content %}

<div>
    <p>Create new author</p>
</div>
<form method="post" action="{% url 'quotes:create_author' %}">
    {% csrf_token %}
    <div>
        <label> Fullname:
            {{ form.fullname }}
        </label>
        <span>{{ form.errors.fullname }}</span>
    </div>
    <div>
        <label>Born date:
            {{ form.born_date }}
        </label>
        <span>{{ form.errors.born_date }}</span>
    </div>
    <div>
        <label>Born_location:
            {{ form.born_location }}
        </label>
        <span>{{ form.errors.born_location }}</span>
    </div>
    <div>
        <label>Description:
            {{ form.description }}
        </label>
        <span>{{ form.errors.description }}</span>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
    </div>
</form>

{% endblock %}

home/quotes/templates/quotes/create_quote.html
{% extends "quotes/base.html" %}

{% block content %}

<div>
    <p>Create new quote</p>
</div>
<form method="post" action="{% url 'quotes:create_quote' %}">
    {% csrf_token %}
    <div>
        <label> Tags:
            {{ form.tags }}
        </label>
        <span>{{ form.errors.tags }}</span>
    </div>
    <div>
        <label>Author:
            {{ form.author }}
        </label>
        <span>{{ form.errors.author }}</span>
    </div>
    <div>
        <label>Quote:
            {{ form.quote }}
        </label>
        <span>{{ form.errors.quote }}</span>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
    </div>
</form>

{% endblock %}

home/quotes/templates/quotes/details.html
{% extends "quotes/base.html" %}

{% block content %}
<div>
    <label>Author:
        <a href="{% url 'quotes:author_detail' author_id=quote.author.author_id %}">Author: {{ quote.author.fullname }}</a>
    </label>
    <label>Quote:
        {{ quote.quote }}
    </label>
    <label>Tags:
        {% for tag in quote.tags %}
            <a href="{% url 'quotes:search_in_tags' tag=tag %}"> {{ tag }}</a>
        {% endfor %}
    </label>
</div>
{% if user.is_authenticated %}
<div>
    <a href="{% url 'quotes:delete' quote_id=quote.quote_id %}" role="button">Delete quote</a>
</div>
{% endif %}
{% endblock %}

home/quotes/templates/quotes/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <title>God of quotes</title>
    <link rel="stylesheet" href="https://unpkg.com/@picocss/pico@latest/css/pico.min.css"/>
    {% load static %}
    <link rel="stylesheet" href="{% static 'quotes/style.css' %}">
</head>
<body>
<main class="container">

    <nav style="margin-bottom: 20px; border-bottom: 2px solid; padding-right: 0px">
        <ul>
            <li><a href="/">Main page</a></li>
            <li><a href="{% url 'quotes:top_ten_tags' %}">Top ten</a></li>
        </ul>
        {% if user.is_authenticated %}
        <ul>
            <li><a href="{% url 'quotes:create_author' %}" role="button">Add author</a></li>
            <li><a href="{% url 'quotes:create_quote' %}" role="button">Add quote</a></li>
            <li><a class="logout" href="{% url 'users:logout' %}">Log out</a></li>
        </ul>
        {% else %}
        <ul>
            <li><a href="{% url 'users:login' %}" role="button">Log in</a></li>
            <li><a href="{% url 'users:register' %}" role="button">Register</a></li>
        </ul>
        {% endif %}
    </nav>
    <h3>{{ text }}</h3>
    {% for quote in quotes %}
    <ul>
        <li><label>Quote: {{ quote.quote }}</label></li>
        <li>
            <label>Tags:
                {% for tag in quote.tags %}
                <a href="{% url 'quotes:search_in_tags' tag=tag %}"> {{ tag }}</a>
                {% endfor %}
            </label>
        </li>
        <li><a href="{% url 'quotes:author_detail' author_id=quote.author.author_id %}">Author: {{ quote.author.fullname }}</a></li>
        <a href="{% url 'quotes:details' quote_id=quote.quote_id %}" role="button">Details</a>
    </ul>
    {% endfor %}
    <span>
        {% if quotes.has_previous %}
            <a href="?page=1">&lt;&lt;first</a>
            <a href="?page={{ quotes.previous_page_number }}">&nbsp;&nbsp;&lt;previous&nbsp;</a>
        {% endif %}

        <span>
            Page {{ quotes.number }} of {{ quotes.paginator.num_pages }}
        </span>

        {% if quotes.has_next %}
            <a href="?page={{ quotes.next_page_number }}">&nbsp;next&gt;&nbsp;&nbsp;</a>
            <a href="?page={{ quotes.paginator.num_pages }}">last&gt;&gt;</a>
        {% endif %}
    </span>
</main>
</body>
</html>

home/quotes/templates/quotes/search_result.html
{% extends "quotes/base.html" %}

{% block content %}
<div>
    <h3>{{ text }}</h3>
    {% for quote in quotes %}
    <ul>
        <li><label>Quote: {{ quote.quote }}</label></li>
        <li>
            <label>Tags:
                {% for tag in quote.tags %}
                <a href="{% url 'quotes:search_in_tags' tag=tag %}"> {{ tag }}</a>
                {% endfor %}
            </label>
        </li>
        <li><a href="{% url 'quotes:author_detail' author_id=quote.author.author_id %}">Author: {{ quote.author.fullname }}</a></li>
        <a href="{% url 'quotes:details' quote_id=quote.quote_id %}" role="button">Details</a>
    </ul>
    {% endfor %}
</div>
{% endblock %}

home/quotes/templates/quotes/top_ten_tags.html
{% extends "quotes/base.html" %}

{% block content %}
<div>
    {% for tag in tags %}
    <ul>
        <li>Tag: <a href="{% url 'quotes:search_in_tags' tag=tag.0 %}">"{{ tag.0 }}"</a> meet {{ tag.1 }} times</li>
    </ul>
    {% endfor %}
</div>
{% endblock %}

home/users/templates/users/login.html
{% extends "quotes/base.html" %}

{% block content %}

{% if messages %}
<div>
    {% for message in messages %}
    <div {% if message.tags %} class="alert-{{ message.tags }}" {% endif %}>{{ message }}</div>
    {% endfor %}
</div>
{% endif %}

<form action="{% url 'users:login' %}" method="post">
    {% csrf_token %}
    <div>
        <label> Username:
            {{ form.username }}
        </label>
    </div>

    <div>
        <label>Password:
            {{ form.password }}
        </label>
    </div>

    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>

{% endblock %}

home/users/templates/users/register.html
{% extends "quotes/base.html" %}

{% block content %}

<div>
    <h2>Registration</h2>
</div>

<form method="post" action="{% url 'users:register' %}">
    {% csrf_token %}
    <div>
        <label> Username:
            {{ form.username }}
        </label>
        <span>{{ form.errors.username }}</span>
    </div>
    <br>
    <div>
        <label>Password:
            {{ form.password1 }}
        </label>
        <span>{{ form.errors.password1 }}</span>
    </div>
    <div>
        <label>Password confirmation:
            {{ form.password2 }}
        </label>
        <span>{{ form.errors.password2 }}</span>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>

{% endblock %}